machinegun_terms = ['AK',
                    'AK 47',
                    'AK-47'
                    'AK47',
                    'AR 18',
                    'AR-18',
                    'AR18'
                    'CZ',
                    'Czech Vz',
                    'FAL',
                    'G3',
                    'Hotchkiss',
                    'KG 9',
                    'KG-9',
                    'KG9'
                    'M 16'
                    'M 1917',
                    'M 1919',
                    'M 240',
                    'M 3',
                    'M 60',
                    'M-16',
                    'M-1917',
                    'M1919'
                    'M-240',
                    'M-3'
                    'M-60'
                    'M1 6',
                    'M1-6',
                    'M16',
                    'M1917',
                    'M1919',
                    'M240',
                    'M3',
                    'M60',
                    'MAC',
                    'MG 34',
                    'MG 42',
                    'MG-34',
                    'MG-42',
                    'MG34',
                    'MG42',
                    'MP 38',
                    'MP 40',
                    'MP 43',
                    'MP 44'
                    'MP 5',
                    'MP 7',
                    'MP-38'
                    'MP-40',
                    'MP-43',
                    'MP-44',
                    'MP-5',
                    'MP-7',
                    'MP38',
                    'MP40',
                    'MP43',
                    'MP44',
                    'MP5',
                    'MP7',
                    'Maxim',
                    'PKM',
                    'PM 98',
                    'PM-98',
                    'PM98'
                    'PPS',
                    'SKS',
                    'SM-10',
                    'SM10',
                    'SM11A1',
                    'STEN',
                    'STG 44'
                    'STG-44',
                    'STG44M-10',
                    'STG44M10',
                    'Scorpion',
                    'Spitfire Carbine',
                    'Sterling',
                    'Swedish K',
                    'Thompson',
                    'Uzi',
                    'Vickers',
                    'Vulcan',
                    'minigun',
                    'readily restored',
                    'select fire',
                    'submachine gun']

silencer_terms = ['Clandestine', 'Oil trap', 'baffles', 'end-caps',
                  'filter adapter', 'freeze plug baffle',
                  'fuel filter adapter', 'muffler', 'oil filter adapter', 'oil trap adapter', 'solvent trap', 'suppressor']

conversion_terms = ['Airsoft conversion',
                    'Auto sear',
                    'DIAS',
                    'Glock chip',
                    'Glock conversion',
                    'Glock sear',
                    'Glock switch',
                    'M16 trigger group',
                    'M2 carbine conversion kit',
                    'conversion kit',
                    'conversion sear',
                    'disconnector',
                    'drop-in auto sear',
                    'lightning link',
                    'sear',
                    'selective fire',
                    'starter gun conversion']

other_terms = ['AOW',
               'Belt buckle gun',
               'H & R Handy Gun',
               'Ithaca Auto & Burglar gun',
               'Marble Game Getter',
               'RPG',
               'SBR',
               'SBS',
               'USAS-12',
               'anti-tank rifle',
               'any other weapon',
               'auto',
               'auto & burglar gun',
               'bazooka',
               'bomb',
               'cane gun',
               'cigarette lighter gun',
               'destructive device',
               'explosive',
               'flare insert',
               'grenade',
               'incendiary',
               'knife gun',
               'large caliber weapon',
               'mine',
               'mortar',
               'pen gun',
               'pengun',
               'poison gas',
               'rocket',
               'rocket launcher',
               'short-barreled rifle',
               'short-barreled shotgun',
               'street sweeper',
               'umbrella gun',
               'vertical hand grip',
               'wallet holster',
               'weapon made from a rifle',
               'weapon made from a shotgun']
